"""Head-to-head demonstration of ConstraintML's real energy/carbon savings.

Trains an identical model/data setup twice:
  - baseline:    GreenTrainer with no budgets at all -- runs the full epoch count.
  - constrained: GreenTrainer with a `deadline` set to 40% of the baseline's actual
                 wall-clock time, plus a loose accuracy guard.

The regression target is generated by a fixed random "teacher" network (not a simple
linear/near-linear function), so the student model's validation loss descends gradually
over roughly the first third of epochs rather than plateauing after 1-2 epochs -- where
exactly to stop is not obvious from a glance, the way an instant plateau would be. Training
past that point yields diminishing, then slightly negative, returns (mild overfitting on
this fixed-size dataset), so stopping at 40% of the baseline's time costs little accuracy
while skipping a real majority of the "diminishing returns" tail -- and therefore uses
real, measurably less energy/carbon.

Note on what this does and doesn't prove: `deadline` here is still a fixed wall-clock
cutoff, calibrated after the fact from the baseline's own timing -- it does not detect
"accuracy has plateaued" the way a human eyeballing the curve would. A hardcoded epoch
count picked by inspecting this same curve would achieve a similar result *for this one
model, on this one machine*. What a hardcoded epoch count can't do is generalize: it has
no relationship to actual wall-clock/energy cost, so the same epoch count means wildly
different resource usage on a different model size or different hardware. `deadline`
(or `energy_budget`/`carbon_budget`) is a real resource constraint that stays meaningful
regardless of those specifics -- that portability, not smarter plateau detection, is v1's
actual differentiator.

`deadline` (not `energy_budget`/`carbon_budget`) is what triggers the early stop here:
ConstraintPlanner projects energy/carbon by extrapolating the CURRENT per-step rate to
the end of the run (see the comment on ConstraintPlanner._project), so a tight
energy/carbon budget would fire almost immediately rather than partway through: deadline
is checked against live elapsed time instead, so it's the lever that actually produces a
"stop once most of the allotted window has passed" effect. energy_budget/carbon_budget
are still passed (with generous headroom) to mirror GreenTrainer's full README signature
and confirm they don't need to bind for this to work.

Run with: python examples/carbon_savings_demo.py
"""

import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

from constraintml import GreenTrainer, TrainingReport
from constraintml.optimization.telemetry.simulated import SimulatedTelemetryCollector


def build_dataset_and_model(
    seed: int = 0,
    n_train: int = 2000,
    n_val: int = 400,
    input_dim: int = 30,
    batch_size: int = 32,
    teacher_hidden: int = 40,
    noise_std: float = 0.3,
):
    """Regression task with a genuinely gradual convergence curve: targets come from a
    fixed random "teacher" network (not a simple linear/near-linear function), so a
    smaller student model can't shortcut its way to the noise floor in 1-2 epochs -- it
    takes real, visible optimization progress over roughly the first third of training.
    """
    torch.manual_seed(seed)

    teacher = nn.Sequential(
        nn.Linear(input_dim, teacher_hidden),
        nn.Tanh(),
        nn.Linear(teacher_hidden, teacher_hidden),
        nn.Tanh(),
        nn.Linear(teacher_hidden, 1),
    )
    for p in teacher.parameters():
        p.requires_grad_(False)

    def make_targets(x: torch.Tensor) -> torch.Tensor:
        with torch.no_grad():
            return teacher(x) + noise_std * torch.randn(x.shape[0], 1)

    x_train = torch.randn(n_train, input_dim)
    y_train = make_targets(x_train)
    x_val = torch.randn(n_val, input_dim)
    y_val = make_targets(x_val)

    train_loader = DataLoader(TensorDataset(x_train, y_train), batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(TensorDataset(x_val, y_val), batch_size=batch_size, shuffle=False)

    def make_model() -> nn.Module:
        model = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1),
        )
        model.load_state_dict(initial_state)
        return model

    # Build one instance to fix an initial weight state, then discard it -- both runs
    # start from these exact weights so the comparison isolates the constraint's effect.
    initial_state = nn.Sequential(
        nn.Linear(input_dim, 64), nn.ReLU(), nn.Linear(64, 32), nn.ReLU(), nn.Linear(32, 1)
    ).state_dict()

    return train_loader, val_loader, make_model, nn.MSELoss()


def run_baseline(
    make_model,
    train_loader,
    val_loader,
    loss_fn,
    max_epochs: int = 25,
    power_watts: float = 250.0,
    evaluate_every_n_steps: int = 10,
    lr: float = 2e-4,
) -> TrainingReport:
    model = make_model()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    trainer = GreenTrainer(
        model=model,
        optimizer=optimizer,
        train_loader=train_loader,
        val_loader=val_loader,
        loss_fn=loss_fn,
        max_epochs=max_epochs,
        telemetry=SimulatedTelemetryCollector(assumed_power_watts=power_watts),
        evaluate_every_n_steps=evaluate_every_n_steps,
    )
    return trainer.train()


def run_constrained(
    baseline_report: TrainingReport,
    make_model,
    train_loader,
    val_loader,
    loss_fn,
    max_epochs: int = 25,
    power_watts: float = 250.0,
    evaluate_every_n_steps: int = 10,
    deadline_fraction: float = 0.4,
    budget_headroom: float = 2.0,
    lr: float = 2e-4,
) -> TrainingReport:
    model = make_model()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    trainer = GreenTrainer(
        model=model,
        optimizer=optimizer,
        train_loader=train_loader,
        val_loader=val_loader,
        loss_fn=loss_fn,
        max_epochs=max_epochs,
        deadline=baseline_report.elapsed_seconds * deadline_fraction,
        # Generous headroom so these never bind -- deadline is the real trigger (see
        # module docstring); still set so the call matches GreenTrainer's full signature.
        energy_budget=baseline_report.energy_kwh * budget_headroom or None,
        carbon_budget=baseline_report.carbon_kgco2e * budget_headroom or None,
        # The "accuracy" proxy is -avg_val_loss, not a percentage -- 0.2 is a loose
        # backstop against a runaway precision drop, not a literal 20%-point bound.
        max_accuracy_loss=0.2,
        telemetry=SimulatedTelemetryCollector(assumed_power_watts=power_watts),
        evaluate_every_n_steps=evaluate_every_n_steps,
    )
    return trainer.train()


def print_comparison(baseline: TrainingReport, constrained: TrainingReport) -> None:
    def pct_saved(base: float, constrained_value: float) -> float:
        if base <= 0:
            return 0.0
        return (base - constrained_value) / base * 100

    energy_saved = pct_saved(baseline.energy_kwh, constrained.energy_kwh)
    carbon_saved = pct_saved(baseline.carbon_kgco2e, constrained.carbon_kgco2e)
    accuracy_delta = (constrained.final_val_accuracy or 0.0) - (baseline.final_val_accuracy or 0.0)

    def row(label, base_value, constrained_value, fmt="{}"):
        print(f"{label:22}{fmt.format(base_value):>18}{fmt.format(constrained_value):>18}")

    print("=" * 72)
    print(f"{'':22}{'Baseline':>18}{'Constrained':>18}")
    print("-" * 72)
    row("Epochs completed", baseline.epochs_completed, constrained.epochs_completed)
    row("Steps completed", baseline.steps_completed, constrained.steps_completed)
    row("Energy (kWh)", baseline.energy_kwh, constrained.energy_kwh, "{:.6f}")
    row("Carbon (kg CO2e)", baseline.carbon_kgco2e, constrained.carbon_kgco2e, "{:.6f}")
    row("Elapsed (s)", baseline.elapsed_seconds, constrained.elapsed_seconds, "{:.2f}")
    row("Final val accuracy*", baseline.final_val_accuracy, constrained.final_val_accuracy, "{:.4f}")
    row("Stopped early", baseline.stopped_early, constrained.stopped_early)
    print("-" * 72)
    print(f"Energy saved:   {energy_saved:6.1f}%")
    print(
        f"Carbon saved:   {carbon_saved:6.1f}%  "
        "(mirrors energy 1:1 -- v1's CarbonModel is a static kg CO2e/kWh multiplier,"
        " not an independent measurement)"
    )
    print(
        f"Accuracy delta: {accuracy_delta:+.4f}  "
        "(constrained vs baseline; *accuracy is -avg validation loss, higher is better)"
    )
    if constrained.stop_reason:
        print(f"Constrained run stopped because: {constrained.stop_reason}")
    print("=" * 72)


def plot_comparison(
    baseline: TrainingReport, constrained: TrainingReport, output_path: str = "examples/carbon_savings_demo.png"
) -> bool:
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print('Install matplotlib to enable charts: pip install -e ".[viz]"')
        return False

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    baseline_epochs = [s.epoch for s in baseline.epoch_history]
    baseline_acc = [s.val_accuracy for s in baseline.epoch_history]
    constrained_epochs = [s.epoch for s in constrained.epoch_history]
    constrained_acc = [s.val_accuracy for s in constrained.epoch_history]

    ax1.plot(baseline_epochs, baseline_acc, marker="o", label="Baseline (no budget)")
    ax1.plot(constrained_epochs, constrained_acc, marker="o", label="Constrained (deadline)")
    if constrained_epochs:
        ax1.axvline(constrained_epochs[-1], color="gray", linestyle="--", label="Constrained stop point")
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("Validation accuracy (-avg loss)")
    ax1.set_title("Accuracy vs. epoch")
    ax1.legend()

    labels = ["Energy (kWh)", "Carbon (kg CO2e)"]
    baseline_values = [baseline.energy_kwh, baseline.carbon_kgco2e]
    constrained_values = [constrained.energy_kwh, constrained.carbon_kgco2e]
    x = list(range(len(labels)))
    width = 0.35
    ax2.bar([i - width / 2 for i in x], baseline_values, width, label="Baseline")
    ax2.bar([i + width / 2 for i in x], constrained_values, width, label="Constrained")
    ax2.set_xticks(x)
    ax2.set_xticklabels(labels)
    ax2.set_title("Resource usage")
    ax2.legend()
    for i, (base_value, constrained_value) in enumerate(zip(baseline_values, constrained_values)):
        if base_value > 0:
            saved = (base_value - constrained_value) / base_value * 100
            ax2.annotate(
                f"-{saved:.0f}%",
                (i + width / 2, constrained_value),
                textcoords="offset points",
                xytext=(0, 5),
                ha="center",
            )

    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)
    print(f"Saved comparison chart to {output_path}")
    return True


def main():
    train_loader, val_loader, make_model, loss_fn = build_dataset_and_model()

    print("Running baseline (no budget, full run)...")
    baseline = run_baseline(make_model, train_loader, val_loader, loss_fn)

    print("Running constrained (GreenTrainer with a deadline at 40% of baseline's wall time)...")
    constrained = run_constrained(baseline, make_model, train_loader, val_loader, loss_fn)

    print_comparison(baseline, constrained)
    plot_comparison(baseline, constrained)


if __name__ == "__main__":
    main()
